//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.WFConfig.Query {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResultOfArrayOfTradeStatementYTXI_Sx5q", Namespace="http://schemas.datacontract.org/2004/07/Em.FundTrade.Query.Entities")]
    [System.SerializableAttribute()]
    public partial class QueryResultOfArrayOfTradeStatementYTXI_Sx5q : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<X.WFConfig.Query.TradeStatement> ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<X.WFConfig.Query.TradeStatement> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeStatement", Namespace="http://schemas.datacontract.org/2004/07/Em.FundTrade.Query.Entities")]
    [System.SerializableAttribute()]
    public partial class TradeStatement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal C_AVAILABLEVOLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal C_AVERAGECOSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_BANKCARDNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_BANKCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime C_CREATETIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_CUSTOMERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime C_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_FUNDCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal C_FUNDNAVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool C_ISDELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool C_ISENABLEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime C_NAVDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_PRODUCTTYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal C_TOTALVOLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime C_UPDATETIMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal C_AVAILABLEVOL {
            get {
                return this.C_AVAILABLEVOLField;
            }
            set {
                if ((this.C_AVAILABLEVOLField.Equals(value) != true)) {
                    this.C_AVAILABLEVOLField = value;
                    this.RaisePropertyChanged("C_AVAILABLEVOL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal C_AVERAGECOST {
            get {
                return this.C_AVERAGECOSTField;
            }
            set {
                if ((this.C_AVERAGECOSTField.Equals(value) != true)) {
                    this.C_AVERAGECOSTField = value;
                    this.RaisePropertyChanged("C_AVERAGECOST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_BANKCARDNO {
            get {
                return this.C_BANKCARDNOField;
            }
            set {
                if ((object.ReferenceEquals(this.C_BANKCARDNOField, value) != true)) {
                    this.C_BANKCARDNOField = value;
                    this.RaisePropertyChanged("C_BANKCARDNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_BANKCODE {
            get {
                return this.C_BANKCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.C_BANKCODEField, value) != true)) {
                    this.C_BANKCODEField = value;
                    this.RaisePropertyChanged("C_BANKCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime C_CREATETIME {
            get {
                return this.C_CREATETIMEField;
            }
            set {
                if ((this.C_CREATETIMEField.Equals(value) != true)) {
                    this.C_CREATETIMEField = value;
                    this.RaisePropertyChanged("C_CREATETIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_CUSTOMERNO {
            get {
                return this.C_CUSTOMERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.C_CUSTOMERNOField, value) != true)) {
                    this.C_CUSTOMERNOField = value;
                    this.RaisePropertyChanged("C_CUSTOMERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime C_DATE {
            get {
                return this.C_DATEField;
            }
            set {
                if ((this.C_DATEField.Equals(value) != true)) {
                    this.C_DATEField = value;
                    this.RaisePropertyChanged("C_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_FUNDCODE {
            get {
                return this.C_FUNDCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.C_FUNDCODEField, value) != true)) {
                    this.C_FUNDCODEField = value;
                    this.RaisePropertyChanged("C_FUNDCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal C_FUNDNAV {
            get {
                return this.C_FUNDNAVField;
            }
            set {
                if ((this.C_FUNDNAVField.Equals(value) != true)) {
                    this.C_FUNDNAVField = value;
                    this.RaisePropertyChanged("C_FUNDNAV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_ID {
            get {
                return this.C_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.C_IDField, value) != true)) {
                    this.C_IDField = value;
                    this.RaisePropertyChanged("C_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool C_ISDEL {
            get {
                return this.C_ISDELField;
            }
            set {
                if ((this.C_ISDELField.Equals(value) != true)) {
                    this.C_ISDELField = value;
                    this.RaisePropertyChanged("C_ISDEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool C_ISENABLED {
            get {
                return this.C_ISENABLEDField;
            }
            set {
                if ((this.C_ISENABLEDField.Equals(value) != true)) {
                    this.C_ISENABLEDField = value;
                    this.RaisePropertyChanged("C_ISENABLED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime C_NAVDATE {
            get {
                return this.C_NAVDATEField;
            }
            set {
                if ((this.C_NAVDATEField.Equals(value) != true)) {
                    this.C_NAVDATEField = value;
                    this.RaisePropertyChanged("C_NAVDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_PRODUCTTYPE {
            get {
                return this.C_PRODUCTTYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.C_PRODUCTTYPEField, value) != true)) {
                    this.C_PRODUCTTYPEField = value;
                    this.RaisePropertyChanged("C_PRODUCTTYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal C_TOTALVOL {
            get {
                return this.C_TOTALVOLField;
            }
            set {
                if ((this.C_TOTALVOLField.Equals(value) != true)) {
                    this.C_TOTALVOLField = value;
                    this.RaisePropertyChanged("C_TOTALVOL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime C_UPDATETIME {
            get {
                return this.C_UPDATETIMEField;
            }
            set {
                if ((this.C_UPDATETIMEField.Equals(value) != true)) {
                    this.C_UPDATETIMEField = value;
                    this.RaisePropertyChanged("C_UPDATETIME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Query.ITradeStatement")]
    public interface ITradeStatement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradeStatement/GetMonthStatementByCustomer", ReplyAction="http://tempuri.org/ITradeStatement/GetMonthStatementByCustomerResponse")]
        X.WFConfig.Query.QueryResultOfArrayOfTradeStatementYTXI_Sx5q GetMonthStatementByCustomer(string customerNo, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradeStatement/GetQuarterStatementByCustomer", ReplyAction="http://tempuri.org/ITradeStatement/GetQuarterStatementByCustomerResponse")]
        X.WFConfig.Query.QueryResultOfArrayOfTradeStatementYTXI_Sx5q GetQuarterStatementByCustomer(string customerNo, int year, int quarter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradeStatement/GetHalfyearStatementByCustomer", ReplyAction="http://tempuri.org/ITradeStatement/GetHalfyearStatementByCustomerResponse")]
        X.WFConfig.Query.QueryResultOfArrayOfTradeStatementYTXI_Sx5q GetHalfyearStatementByCustomer(string customerNo, int year, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradeStatement/GetYearStatementByCustomer", ReplyAction="http://tempuri.org/ITradeStatement/GetYearStatementByCustomerResponse")]
        X.WFConfig.Query.QueryResultOfArrayOfTradeStatementYTXI_Sx5q GetYearStatementByCustomer(string customerNo, int year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITradeStatementChannel : X.WFConfig.Query.ITradeStatement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TradeStatementClient : System.ServiceModel.ClientBase<X.WFConfig.Query.ITradeStatement>, X.WFConfig.Query.ITradeStatement {
        
        public TradeStatementClient() {
        }
        
        public TradeStatementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TradeStatementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradeStatementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradeStatementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public X.WFConfig.Query.QueryResultOfArrayOfTradeStatementYTXI_Sx5q GetMonthStatementByCustomer(string customerNo, int year, int month) {
            return base.Channel.GetMonthStatementByCustomer(customerNo, year, month);
        }
        
        public X.WFConfig.Query.QueryResultOfArrayOfTradeStatementYTXI_Sx5q GetQuarterStatementByCustomer(string customerNo, int year, int quarter) {
            return base.Channel.GetQuarterStatementByCustomer(customerNo, year, quarter);
        }
        
        public X.WFConfig.Query.QueryResultOfArrayOfTradeStatementYTXI_Sx5q GetHalfyearStatementByCustomer(string customerNo, int year, int type) {
            return base.Channel.GetHalfyearStatementByCustomer(customerNo, year, type);
        }
        
        public X.WFConfig.Query.QueryResultOfArrayOfTradeStatementYTXI_Sx5q GetYearStatementByCustomer(string customerNo, int year) {
            return base.Channel.GetYearStatementByCustomer(customerNo, year);
        }
    }
}
